version: '3.8'

services:
  spark-master:
    container_name: irah-spark-master
    build: .
    image: spark-image
    user: root
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./spark_apps:/opt/spark/apps:z
      - spark-logs:/opt/spark/spark-events:z
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    container_name: irah-spark-history
    image: spark-image
    user: root
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events:z
    ports:
      - '18080:18080'

  spark-worker:
#    container_name: da-spark-worker
    image: spark-image
    user: root
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./spark_apps:/opt/spark/apps:z
      - spark-logs:/opt/spark/spark-events:z

volumes:
  spark-logs:
